### ISSUE TITLE
Changing Cargo.toml `package.version` impacts `Module.hash`

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#145]
Noticed when changing the `version` of `Cargo.toml` (no other code changes) the Substream `Module.hash` is different.

❓ **QUESTION:** is this intentional? If so, that would mean any version updates would force re-caching all maps & stores.

## Steps used to build

```
cargo build --target wasm32-unknown-unknown --release
substreams pack ./substreams.yaml
substreams info example.spkg
```

## `Cargo.toml` (Before)
```toml
[package]
name = "example"
version = "0.1.0"
edition = "2021"
```

```bash
Name: db_out
Initial block: 0
Kind: map
Output Type: proto:sf.substreams.database.v1.DatabaseChanges
Hash: d41c798b276c996882d9293459d77ee29dfccd54
```

## `Cargo.toml` (After)
```toml
[package]
name = "example"
version = "0.1.1"
edition = "2021"
```

```
Name: db_out
Initial block: 0
Kind: map
Output Type: proto:sf.substreams.database.v1.DatabaseChanges
❌ Hash: 8dbcda80af688ef20a895b4833cea57333b78f5e
```
