### ISSUE TITLE
Map module receiving input from 2 differently typed stores gives out wrong operation type in Deltas

### ISSUE THREAD

**Issue by let4be** [streamingfast/substreams#158]
I have following modules defined:
```yaml
  - name: transfer_map
    kind: map
    inputs:
      - source: sf.ethereum.type.v2.Block
    output:
      type: proto:beepro.ethereum.bsc.bep20.v1.Transfers

  - name: transfer_balance_store
    kind: store
    updatePolicy: add
    valueType: bigint
    inputs:
      - map: transfer_map

  - name: transfer_store
    kind: store
    updatePolicy: set
    valueType: proto:beepro.ethereum.bsc.bep20.v1.Transfer
    inputs:
      - map: transfer_map

  - name: transfer_db_out
    kind: map
    inputs:
      - store: transfer_balance_store
        mode: deltas
      - store: transfer_store
        mode: deltas
    output:
      type: proto:sf.substreams.database.v1.DatabaseChanges
```

 now in my Rust code:
```rust

#[substreams::handlers::map]
fn transfer_db_out(balance: store::Deltas<DeltaBigInt>, transfer: store::Deltas<DeltaProto<Transfer>>) -> Result<DatabaseChanges, Error>  {
	let mut database_changes: DatabaseChanges = Default::default();

	db::balance_delta_to_database_changes(&mut database_changes, balance);
	db::transfer_delta_to_database_changes(&mut database_changes, transfer);

	Ok(database_changes)
}
```

here deltas for `balance` are NEVER create, always update and so I cannot insert anything in DB... Why is this happening?
P.S. I want to insert into 2 different tables(one for balances and one for transfers)

I could of course run several substreams - one for balances and another one for transfers, but it seems very wasteful... why process exactly the same data twice?

There will be other data collection, ideally I would like to process one block exactly once and extract all data I need... is this even possible in current substreams impl?
