### ISSUE TITLE
Store miss-match

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams#185]
```
- name: map_tokens_entities
  kind: map
  initialBlock: 12369621
  inputs:
    - map: map_pools_created
    - store: store_pools # <- ça c'est un store de type Proto<Pool>
    - store: store_swaps_volume
      mode: deltas
    - store: store_total_tx_counts
      mode: deltas
    - store: store_total_value_locked_by_tokens
      mode: deltas
    - store: store_total_value_locked
      mode: deltas
    - store: store_eth_prices
      mode: deltas
    - store: store_tokens_whitelist_pools
      mode: deltas
  output:
    type: proto:substreams.entity.v1.EntityChanges
```

Dans mon module map_tokens_entities je m’attends à un Store de type Int64 à la place du store_pools. Bizarrement ya rien qui a pété et dans mon substreams quand je fais un .get_last(…)  ça me retourne None…

Basically, un missmatch de 2 type de store mais rien qui me pète dans la face
