### ISSUE TITLE
⚠️ WARN    Plugin "buf.build/prost/prost" is deprecated

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#236]
### Command `make protogen`

```
WARN    Plugin "buf.build/prost/prost" is deprecated
WARN    Plugin "buf.build/prost/crate" is deprecated
```

**Cargo.toml**

```toml
[dependencies]
prost = "0.11"
prost-types = "0.11"
substreams = "0.5"
```
