### ISSUE TITLE
update `deriveFrom` example

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#349]
## Update example for `deriveFrom`
- [ ] package.name = underscore
- [ ] version = include "v"

### Issues
- [ ] unable to get package: failed validation: package validation failed: 
```
 eth-substreams gui erc20-balance-changes-1.1.0.spkg graph_out
Error: read manifest "erc20-balance-changes-1.1.0.spkg": unable to get package: failed validation: package validation failed: package "erc20-balance-changes": invalid name: must match ^([a-zA-Z][a-zA-Z0-9_]{0,63})$
```
- [ ] should match Semver
```bash
eth-substreams gui erc20-balance-changes-1.1.0.spkg graph_out
Error: read manifest "erc20-balance-changes-1.1.0.spkg": unable to get package: failed validation: package validation failed: package "erc20_balance_changes": version "1.1.0" should match Semver
```

### References

- https://substreams.streamingfast.io/quick-access/change-log#changed-3
- https://github.com/streamingfast/substreams/issues/271

## Not working example ❌ 

```yaml
deriveFrom: path/to/mainnet-substreams.spkg #this can also be a remote url

package:
  name: "polygon-substreams"
  version: "100.0.0"

network: polygon

initialBlocks:
  module1: 17500000
params:
  module1: "address=2a75ca72679cf1299936d6104d825c9654489058"
```

## Working example ✅ 

```yaml
deriveFrom: path/to/mainnet-substreams.spkg #this can also be a remote url

package:
  name: polygon_substreams
  version: v100.0.0

network: polygon

initialBlocks:
  module1: 17500000
params:
  module1: "address=2a75ca72679cf1299936d6104d825c9654489058"
```
