### ISSUE TITLE
Codegen: support dynamic datasources

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#359]
substreams.gen.yaml <--- file for code generation, maybe better than the interactive experience
```yaml
name: my-substreams
chain: mainnet
contracts:
  - name: “token”
    address: 0x5678567856785678567856785678567856785678
    abi: “token.abi.json” # optional, if not provided, will be fetched from Etherscan
  - name: “pair”
    addressesFromFactory:
      name: “factory”
      eventName: “PairCreated”
      eventParam: “pool”
    abi:
      file: “paircontract.abi.json” # optional, if not provided, will be fetched from Etherscan
  - name: “factory”
    address: 0x1234123412341234123412341234123412341234
    abi:
      file: “factory.abi.json”
```
