### ISSUE TITLE
Create a substreams module that filters out (reduce) the event logs based on the same language as the blockindex

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#415]
# Dependencies

#409 #410 ... #413 #414

# TODO

- [ ] Create the module (inputs: (param, array of sf.ethereum.type.v2.Log)  and outputs: (array of sf.ethereum.type.v2.Log) -- see #414 to see the module that actually extracts the events
- [ ] The module should use the param and parse it exactly like the log blockIndex filter string, but it filters at the transaction level instead of at the block level!

Something like this:

```yaml
imports:
  eth_events_extractor: https://spkg.io/streamingfast/eth-events-extractor-v1.0.0.spkg

modules:
- name: eth_events_filter
  inputs:
  - params: string
  - map: eth_events_extractor:map_events
  output: proto:sf.ethereum.type.v2.ArrayOfLogs
```

* With this cool pattern, someone can depend on this module like this:

```yaml
imports:
  eth_block_filters: https://spkg.io/streamingfast/eth-block-filters-v1.0.0.spkg
  eth_filter: https://spkg.io/streamingfast/eth-filters-v1.0.0.spkg
  
- name: my-cool-mapper
  blockFilter:
    module: eth_block_filters:event_filter
    query: "(addr:USDC || addr:PANCAKE) && (evsig:Transfer || evsig:TransferFrom)" 
  inputs:
  - map: eth_events_filter:map_events
  outputs:
  - proto: some.sql.format
 
params:
  eth_filters:eth_events_filter: "(addr:USDC || addr:PANCAKE) && (evsig:Transfer || evsig:TransferFrom)"
```
