### ISSUE TITLE
Bug: invalid store operation "set", only valid for stores with updatePolicy == "replace", wasm execution failed deterministically

### ISSUE THREAD

**Issue by vinhloc30796** [streamingfast/substreams#620]
Shouldn't operation "set" be available to updatePolicy "set"?

my code:
```
- name: store_something
  kind: store
  updatePolicy: set
  valueType: proto:something
  inputs:
    - map: transform_something
```
